"""Monster attack table generated from NetHack 3.6.6 monst.c by dev/survival/gen_mon_attacks.py (do not edit).

MON_ATTACKS[name] = (level, speed, difficulty, [(attack type, damage type, dice n, dice d), ...])
"""

MON_ATTACKS = {
    'Aleax': (10, 8, 12, [('AT_WEAP', 'AD_PHYS', 1, 6), ('AT_WEAP', 'AD_PHYS', 1, 6), ('AT_KICK', 'AD_PHYS', 1, 4)]),
    'Angel': (14, 10, 19, [('AT_WEAP', 'AD_PHYS', 1, 6), ('AT_WEAP', 'AD_PHYS', 1, 6), ('AT_CLAW', 'AD_PHYS', 1, 4), ('AT_MAGC', 'AD_MAGM', 2, 6)]),
    'Arch Priest': (25, 12, 30, [('AT_WEAP', 'AD_PHYS', 4, 10), ('AT_KICK', 'AD_PHYS', 2, 8), ('AT_MAGC', 'AD_CLRC', 2, 8), ('AT_MAGC', 'AD_CLRC', 2, 8)]),
    'Archon': (19, 16, -1, [('AT_WEAP', 'AD_PHYS', 2, 4), ('AT_WEAP', 'AD_PHYS', 2, 4), ('AT_GAZE', 'AD_BLND', 2, 6), ('AT_CLAW', 'AD_PHYS', 1, 8), ('AT_MAGC', 'AD_SPEL', 4, 6)]),
    'Ashikaga Takauji': (15, 12, -1, [('AT_WEAP', 'AD_PHYS', 2, 6), ('AT_WEAP', 'AD_PHYS', 2, 6), ('AT_CLAW', 'AD_SAMU', 2, 6)]),
    'Asmodeus': (105, 12, -1, [('AT_CLAW', 'AD_PHYS', 4, 4), ('AT_MAGC', 'AD_COLD', 6, 6)]),
    'Baalzebub': (89, 9, -1, [('AT_BITE', 'AD_DRST', 2, 6), ('AT_GAZE', 'AD_STUN', 2, 6)]),
    'Cerberus': (12, 10, -1, [('AT_BITE', 'AD_PHYS', 3, 6), ('AT_BITE', 'AD_PHYS', 3, 6), ('AT_BITE', 'AD_PHYS', 3, 6)]),
    'Charon': (76, 18, -1, [('AT_WEAP', 'AD_PHYS', 1, 8), ('AT_TUCH', 'AD_PLYS', 1, 8)]),
    'Chromatic Dragon': (16, 12, -1, [('AT_BREA', 'AD_RBRE', 6, 6), ('AT_MAGC', 'AD_SPEL', 0, 0), ('AT_CLAW', 'AD_SAMU', 2, 8), ('AT_BITE', 'AD_PHYS', 4, 8), ('AT_BITE', 'AD_PHYS', 4, 8), ('AT_STNG', 'AD_PHYS', 1, 6)]),
    'Croesus': (20, 15, -1, [('AT_WEAP', 'AD_PHYS', 4, 10)]),
    'Cyclops': (18, 12, 23, [('AT_WEAP', 'AD_PHYS', 4, 8), ('AT_WEAP', 'AD_PHYS', 4, 8), ('AT_CLAW', 'AD_SAMU', 2, 6)]),
    'Dark One': (15, 12, 20, [('AT_WEAP', 'AD_PHYS', 1, 6), ('AT_WEAP', 'AD_PHYS', 1, 6), ('AT_CLAW', 'AD_SAMU', 1, 4), ('AT_MAGC', 'AD_SPEL', 0, 0)]),
    'Death': (30, 12, -1, [('AT_TUCH', 'AD_DETH', 8, 8), ('AT_TUCH', 'AD_DETH', 8, 8)]),
    'Demogorgon': (106, 15, -1, [('AT_MAGC', 'AD_SPEL', 8, 6), ('AT_STNG', 'AD_DRLI', 1, 4), ('AT_CLAW', 'AD_DISE', 1, 6), ('AT_CLAW', 'AD_DISE', 1, 6)]),
    'Dispater': (78, 15, -1, [('AT_WEAP', 'AD_PHYS', 4, 6), ('AT_MAGC', 'AD_SPEL', 6, 6)]),
    'Earendil': (20, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 8)]),
    'Elvenking': (9, 12, -1, [('AT_WEAP', 'AD_PHYS', 2, 4), ('AT_WEAP', 'AD_PHYS', 2, 4)]),
    'Elwing': (20, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 8)]),
    'Famine': (30, 12, -1, [('AT_TUCH', 'AD_FAMN', 8, 8), ('AT_TUCH', 'AD_FAMN', 8, 8)]),
    'Geryon': (72, 3, -1, [('AT_CLAW', 'AD_PHYS', 3, 6), ('AT_CLAW', 'AD_PHYS', 3, 6), ('AT_STNG', 'AD_DRST', 2, 4)]),
    'Goblin King': (15, 12, -1, [('AT_WEAP', 'AD_PHYS', 2, 6), ('AT_WEAP', 'AD_PHYS', 2, 6), ('AT_CLAW', 'AD_SAMU', 1, 6)]),
    'Grand Master': (25, 12, 30, [('AT_CLAW', 'AD_PHYS', 4, 10), ('AT_KICK', 'AD_PHYS', 2, 8), ('AT_MAGC', 'AD_CLRC', 2, 8), ('AT_MAGC', 'AD_CLRC', 2, 8)]),
    'Green-elf': (5, 12, 7, [('AT_WEAP', 'AD_PHYS', 2, 4)]),
    'Grey-elf': (6, 12, 8, [('AT_WEAP', 'AD_PHYS', 2, 4)]),
    'High-elf': (5, 12, -1, [('AT_WEAP', 'AD_PHYS', 2, 4), ('AT_MAGC', 'AD_CLRC', 0, 0)]),
    'Hippocrates': (20, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'Ixoth': (15, 12, 22, [('AT_BREA', 'AD_FIRE', 8, 6), ('AT_BITE', 'AD_PHYS', 4, 8), ('AT_MAGC', 'AD_SPEL', 0, 0), ('AT_CLAW', 'AD_PHYS', 2, 4), ('AT_CLAW', 'AD_SAMU', 2, 4)]),
    'Juiblex': (50, 3, 26, [('AT_ENGL', 'AD_DISE', 4, 10), ('AT_SPIT', 'AD_ACID', 3, 6)]),
    'Keystone Kop': (1, 6, 3, [('AT_WEAP', 'AD_PHYS', 1, 4)]),
    'King Arthur': (20, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 6), ('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'Kop Kaptain': (4, 12, -1, [('AT_WEAP', 'AD_PHYS', 2, 6)]),
    'Kop Lieutenant': (3, 10, 5, [('AT_WEAP', 'AD_PHYS', 1, 8)]),
    'Kop Sergeant': (2, 8, 4, [('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'Lord Carnarvon': (20, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'Lord Sato': (20, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 8), ('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'Lord Surtur': (15, 12, -1, [('AT_WEAP', 'AD_PHYS', 2, 10), ('AT_WEAP', 'AD_PHYS', 2, 10), ('AT_CLAW', 'AD_SAMU', 2, 6)]),
    'Master Assassin': (15, 12, -1, [('AT_WEAP', 'AD_DRST', 2, 6), ('AT_WEAP', 'AD_PHYS', 2, 8), ('AT_CLAW', 'AD_SAMU', 2, 6)]),
    'Master Kaen': (25, 12, -1, [('AT_CLAW', 'AD_PHYS', 16, 2), ('AT_CLAW', 'AD_PHYS', 16, 2), ('AT_MAGC', 'AD_CLRC', 0, 0), ('AT_CLAW', 'AD_SAMU', 1, 4)]),
    'Master of Thieves': (20, 12, -1, [('AT_WEAP', 'AD_PHYS', 2, 6), ('AT_WEAP', 'AD_PHYS', 2, 6), ('AT_CLAW', 'AD_SAMU', 2, 4)]),
    'Medusa': (20, 12, 25, [('AT_WEAP', 'AD_PHYS', 2, 4), ('AT_CLAW', 'AD_PHYS', 1, 8), ('AT_GAZE', 'AD_STON', 0, 0), ('AT_BITE', 'AD_DRST', 1, 6)]),
    'Minion of Huhetotl': (16, 12, 23, [('AT_WEAP', 'AD_PHYS', 8, 4), ('AT_WEAP', 'AD_PHYS', 4, 6), ('AT_MAGC', 'AD_SPEL', 0, 0), ('AT_CLAW', 'AD_SAMU', 2, 6)]),
    'Mordor orc': (3, 5, 5, [('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'Nalzok': (16, 12, 23, [('AT_WEAP', 'AD_PHYS', 8, 4), ('AT_WEAP', 'AD_PHYS', 4, 6), ('AT_MAGC', 'AD_SPEL', 0, 0), ('AT_CLAW', 'AD_SAMU', 2, 6)]),
    'Nazgul': (13, 12, -1, [('AT_WEAP', 'AD_DRLI', 1, 4), ('AT_BREA', 'AD_SLEE', 2, 25)]),
    'Neferet the Green': (20, 12, 23, [('AT_WEAP', 'AD_PHYS', 1, 6), ('AT_MAGC', 'AD_SPEL', 2, 8)]),
    'Norn': (20, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 8), ('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'Olog-hai': (13, 12, -1, [('AT_WEAP', 'AD_PHYS', 3, 6), ('AT_CLAW', 'AD_PHYS', 2, 8), ('AT_BITE', 'AD_PHYS', 2, 6)]),
    'Oracle': (12, 0, -1, [('AT_NONE', 'AD_MAGM', 0, 4)]),
    'Orcus': (66, 9, -1, [('AT_WEAP', 'AD_PHYS', 3, 6), ('AT_CLAW', 'AD_PHYS', 3, 4), ('AT_CLAW', 'AD_PHYS', 3, 4), ('AT_MAGC', 'AD_SPEL', 8, 6), ('AT_STNG', 'AD_DRST', 2, 4)]),
    'Orion': (20, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'Pelias': (20, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'Pestilence': (30, 12, -1, [('AT_TUCH', 'AD_PEST', 8, 8), ('AT_TUCH', 'AD_PEST', 8, 8)]),
    'Scorpius': (15, 12, -1, [('AT_CLAW', 'AD_PHYS', 2, 6), ('AT_CLAW', 'AD_SAMU', 2, 6), ('AT_STNG', 'AD_DISE', 1, 4)]),
    'Shaman Karnov': (20, 12, -1, [('AT_WEAP', 'AD_PHYS', 2, 4)]),
    'Thoth Amon': (16, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 6), ('AT_MAGC', 'AD_SPEL', 0, 0), ('AT_MAGC', 'AD_SPEL', 0, 0), ('AT_CLAW', 'AD_SAMU', 1, 4)]),
    'Twoflower': (20, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 6), ('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'Uruk-hai': (3, 7, 5, [('AT_WEAP', 'AD_PHYS', 1, 8)]),
    'Vlad the Impaler': (28, 26, -1, [('AT_WEAP', 'AD_PHYS', 2, 10), ('AT_BITE', 'AD_DRLI', 1, 12)]),
    'Woodland-elf': (4, 12, 6, [('AT_WEAP', 'AD_PHYS', 2, 4)]),
    'Yeenoghu': (56, 18, -1, [('AT_WEAP', 'AD_PHYS', 3, 6), ('AT_WEAP', 'AD_CONF', 2, 8), ('AT_CLAW', 'AD_PLYS', 1, 6), ('AT_MAGC', 'AD_MAGM', 2, 6)]),
    'abbot': (5, 12, -1, [('AT_CLAW', 'AD_PHYS', 8, 2), ('AT_KICK', 'AD_STUN', 3, 2), ('AT_MAGC', 'AD_CLRC', 0, 0)]),
    'acid blob': (1, 3, 2, [('AT_NONE', 'AD_ACID', 1, 8)]),
    'acolyte': (5, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 6), ('AT_MAGC', 'AD_CLRC', 0, 0)]),
    'air elemental': (8, 36, 10, [('AT_ENGL', 'AD_PHYS', 1, 10)]),
    'aligned priest': (12, 12, 15, [('AT_WEAP', 'AD_PHYS', 4, 10), ('AT_KICK', 'AD_PHYS', 1, 4), ('AT_MAGC', 'AD_CLRC', 0, 0)]),
    'ape': (4, 12, 6, [('AT_CLAW', 'AD_PHYS', 1, 3), ('AT_CLAW', 'AD_PHYS', 1, 3), ('AT_BITE', 'AD_PHYS', 1, 6)]),
    'apprentice': (5, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 6), ('AT_MAGC', 'AD_SPEL', 0, 0)]),
    'arch-lich': (25, 9, -1, [('AT_TUCH', 'AD_COLD', 5, 6), ('AT_MAGC', 'AD_SPEL', 0, 0)]),
    'archeologist': (10, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 6), ('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'attendant': (5, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'baby black dragon': (12, 9, 13, [('AT_BITE', 'AD_PHYS', 2, 6)]),
    'baby blue dragon': (12, 9, 13, [('AT_BITE', 'AD_PHYS', 2, 6)]),
    'baby crocodile': (3, 6, 4, [('AT_BITE', 'AD_PHYS', 1, 4)]),
    'baby gray dragon': (12, 9, 13, [('AT_BITE', 'AD_PHYS', 2, 6)]),
    'baby green dragon': (12, 9, 13, [('AT_BITE', 'AD_PHYS', 2, 6)]),
    'baby long worm': (5, 3, 6, [('AT_BITE', 'AD_PHYS', 1, 4)]),
    'baby orange dragon': (12, 9, 13, [('AT_BITE', 'AD_PHYS', 2, 6)]),
    'baby purple worm': (8, 3, 9, [('AT_BITE', 'AD_PHYS', 1, 6)]),
    'baby red dragon': (12, 9, 13, [('AT_BITE', 'AD_PHYS', 2, 6)]),
    'baby shimmering dragon': (12, 9, -1, [('AT_BITE', 'AD_PHYS', 2, 6)]),
    'baby silver dragon': (12, 9, -1, [('AT_BITE', 'AD_PHYS', 2, 6)]),
    'baby white dragon': (12, 9, 13, [('AT_BITE', 'AD_PHYS', 2, 6)]),
    'baby yellow dragon': (12, 9, 13, [('AT_BITE', 'AD_PHYS', 2, 6)]),
    'balrog': (16, 5, 20, [('AT_WEAP', 'AD_PHYS', 8, 4), ('AT_WEAP', 'AD_PHYS', 4, 6)]),
    'baluchitherium': (14, 12, 15, [('AT_CLAW', 'AD_PHYS', 5, 4), ('AT_CLAW', 'AD_PHYS', 5, 4)]),
    'barbarian': (10, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 6), ('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'barbed devil': (8, 12, 10, [('AT_CLAW', 'AD_PHYS', 2, 4), ('AT_CLAW', 'AD_PHYS', 2, 4), ('AT_STNG', 'AD_PHYS', 3, 4)]),
    'barrow wight': (3, 12, 7, [('AT_WEAP', 'AD_DRLI', 0, 0), ('AT_MAGC', 'AD_SPEL', 0, 0), ('AT_CLAW', 'AD_PHYS', 1, 4)]),
    'bat': (0, 22, 2, [('AT_BITE', 'AD_PHYS', 1, 4)]),
    'beholder': (6, 3, -1, [('AT_GAZE', 'AD_SLOW', 0, 0), ('AT_GAZE', 'AD_SLEE', 2, 25), ('AT_GAZE', 'AD_DISN', 0, 0), ('AT_GAZE', 'AD_STON', 0, 0), ('AT_GAZE', 'AD_CNCL', 2, 4), ('AT_BITE', 'AD_PHYS', 2, 4)]),
    'black dragon': (15, 9, 20, [('AT_BREA', 'AD_DISN', 1, 255), ('AT_BITE', 'AD_PHYS', 3, 8), ('AT_CLAW', 'AD_PHYS', 1, 4), ('AT_CLAW', 'AD_PHYS', 1, 4)]),
    'black light': (5, 15, 7, [('AT_EXPL', 'AD_HALU', 10, 12)]),
    'black naga': (8, 14, 10, [('AT_BITE', 'AD_PHYS', 2, 6), ('AT_SPIT', 'AD_ACID', 0, 0)]),
    'black naga hatchling': (3, 10, 4, [('AT_BITE', 'AD_PHYS', 1, 4)]),
    'black pudding': (10, 6, 12, [('AT_BITE', 'AD_CORR', 3, 8), ('AT_NONE', 'AD_CORR', 0, 0)]),
    'black unicorn': (4, 24, 6, [('AT_BUTT', 'AD_PHYS', 1, 12), ('AT_KICK', 'AD_PHYS', 1, 6)]),
    'blue dragon': (15, 9, 20, [('AT_BREA', 'AD_ELEC', 4, 6), ('AT_BITE', 'AD_PHYS', 3, 8), ('AT_CLAW', 'AD_PHYS', 1, 4), ('AT_CLAW', 'AD_PHYS', 1, 4)]),
    'blue jelly': (4, 0, 5, [('AT_NONE', 'AD_COLD', 0, 6)]),
    'bone devil': (9, 15, 13, [('AT_WEAP', 'AD_PHYS', 3, 4), ('AT_STNG', 'AD_DRST', 2, 4)]),
    'brown mold': (1, 0, 2, [('AT_NONE', 'AD_COLD', 0, 6)]),
    'brown pudding': (5, 3, 6, [('AT_BITE', 'AD_DCAY', 0, 0)]),
    'bugbear': (3, 9, 5, [('AT_WEAP', 'AD_PHYS', 2, 4)]),
    'captain': (12, 10, 14, [('AT_WEAP', 'AD_PHYS', 4, 4), ('AT_WEAP', 'AD_PHYS', 4, 4)]),
    'carnivorous ape': (6, 12, 8, [('AT_CLAW', 'AD_PHYS', 1, 4), ('AT_CLAW', 'AD_PHYS', 1, 4), ('AT_HUGS', 'AD_PHYS', 1, 8)]),
    'cave spider': (1, 12, 3, [('AT_BITE', 'AD_PHYS', 1, 2)]),
    'caveman': (10, 12, -1, [('AT_WEAP', 'AD_PHYS', 2, 4)]),
    'cavewoman': (10, 12, -1, [('AT_WEAP', 'AD_PHYS', 2, 4)]),
    'centipede': (2, 4, 4, [('AT_BITE', 'AD_DRST', 1, 3)]),
    'chameleon': (6, 5, 7, [('AT_BITE', 'AD_PHYS', 4, 2)]),
    'chickatrice': (4, 4, 7, [('AT_BITE', 'AD_PHYS', 1, 2), ('AT_TUCH', 'AD_STON', 0, 0), ('AT_NONE', 'AD_STON', 0, 0)]),
    'chieftain': (5, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'clay golem': (11, 7, 12, [('AT_CLAW', 'AD_PHYS', 3, 10)]),
    'cobra': (6, 18, 10, [('AT_BITE', 'AD_DRST', 2, 4), ('AT_SPIT', 'AD_BLND', 0, 0)]),
    'cockatrice': (5, 6, 8, [('AT_BITE', 'AD_PHYS', 1, 3), ('AT_TUCH', 'AD_STON', 0, 0), ('AT_NONE', 'AD_STON', 0, 0)]),
    'couatl': (8, 10, 11, [('AT_BITE', 'AD_DRST', 2, 4), ('AT_BITE', 'AD_PHYS', 1, 3), ('AT_HUGS', 'AD_WRAP', 2, 4)]),
    'coyote': (1, 12, 2, [('AT_BITE', 'AD_PHYS', 1, 4)]),
    'crocodile': (6, 9, 7, [('AT_BITE', 'AD_PHYS', 4, 2), ('AT_CLAW', 'AD_PHYS', 1, 12)]),
    'demilich': (14, 9, 18, [('AT_TUCH', 'AD_COLD', 3, 4), ('AT_MAGC', 'AD_SPEL', 0, 0)]),
    'dingo': (4, 16, 5, [('AT_BITE', 'AD_PHYS', 1, 6)]),
    'disenchanter': (12, 12, 14, [('AT_CLAW', 'AD_ENCH', 4, 4), ('AT_NONE', 'AD_ENCH', 0, 0)]),
    'djinni': (7, 12, 8, [('AT_WEAP', 'AD_PHYS', 2, 8)]),
    'dog': (4, 16, -1, [('AT_BITE', 'AD_PHYS', 1, 6)]),
    'doppelganger': (9, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 12)]),
    'dust vortex': (4, 20, 6, [('AT_ENGL', 'AD_BLND', 2, 8)]),
    'dwarf': (2, 6, 4, [('AT_WEAP', 'AD_PHYS', 1, 8)]),
    'dwarf king': (6, 6, -1, [('AT_WEAP', 'AD_PHYS', 2, 6), ('AT_WEAP', 'AD_PHYS', 2, 6)]),
    'dwarf lord': (4, 6, 6, [('AT_WEAP', 'AD_PHYS', 2, 4), ('AT_WEAP', 'AD_PHYS', 2, 4)]),
    'dwarf mummy': (5, 10, 6, [('AT_CLAW', 'AD_PHYS', 1, 6)]),
    'dwarf zombie': (2, 6, 3, [('AT_CLAW', 'AD_PHYS', 1, 6)]),
    'earth elemental': (8, 6, 10, [('AT_CLAW', 'AD_PHYS', 4, 6)]),
    'electric eel': (7, 10, 10, [('AT_BITE', 'AD_ELEC', 4, 6), ('AT_TUCH', 'AD_WRAP', 0, 0)]),
    'elf': (10, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 8)]),
    'elf mummy': (6, 12, 7, [('AT_CLAW', 'AD_PHYS', 2, 4)]),
    'elf zombie': (3, 6, 4, [('AT_CLAW', 'AD_PHYS', 1, 7)]),
    'elf-lord': (8, 12, 11, [('AT_WEAP', 'AD_PHYS', 2, 4), ('AT_WEAP', 'AD_PHYS', 2, 4)]),
    'energy vortex': (6, 20, -1, [('AT_ENGL', 'AD_ELEC', 1, 6), ('AT_ENGL', 'AD_DREN', 2, 6), ('AT_NONE', 'AD_ELEC', 0, 4)]),
    'erinys': (7, 12, 10, [('AT_WEAP', 'AD_DRST', 2, 4)]),
    'ettin': (10, 12, 13, [('AT_WEAP', 'AD_PHYS', 2, 8), ('AT_WEAP', 'AD_PHYS', 3, 6)]),
    'ettin mummy': (7, 12, 8, [('AT_CLAW', 'AD_PHYS', 2, 6), ('AT_CLAW', 'AD_PHYS', 2, 6)]),
    'ettin zombie': (6, 8, 7, [('AT_CLAW', 'AD_PHYS', 1, 10), ('AT_CLAW', 'AD_PHYS', 1, 10)]),
    'fire ant': (3, 18, 6, [('AT_BITE', 'AD_PHYS', 2, 4), ('AT_BITE', 'AD_FIRE', 2, 4)]),
    'fire elemental': (8, 12, 10, [('AT_CLAW', 'AD_FIRE', 3, 6), ('AT_NONE', 'AD_FIRE', 0, 4)]),
    'fire giant': (9, 12, 11, [('AT_WEAP', 'AD_PHYS', 2, 10)]),
    'fire vortex': (8, 22, 10, [('AT_ENGL', 'AD_FIRE', 1, 10), ('AT_NONE', 'AD_FIRE', 0, 4)]),
    'flaming sphere': (6, 13, 8, [('AT_EXPL', 'AD_FIRE', 4, 6)]),
    'flesh golem': (9, 8, 10, [('AT_CLAW', 'AD_PHYS', 2, 8), ('AT_CLAW', 'AD_PHYS', 2, 8)]),
    'floating eye': (2, 1, 3, [('AT_NONE', 'AD_PLYS', 0, 70)]),
    'fog cloud': (3, 1, 4, [('AT_ENGL', 'AD_PHYS', 1, 6)]),
    'forest centaur': (5, 18, 8, [('AT_WEAP', 'AD_PHYS', 1, 8), ('AT_KICK', 'AD_PHYS', 1, 6)]),
    'fox': (0, 15, 1, [('AT_BITE', 'AD_PHYS', 1, 3)]),
    'freezing sphere': (6, 13, 8, [('AT_EXPL', 'AD_COLD', 4, 6)]),
    'frost giant': (10, 12, 13, [('AT_WEAP', 'AD_PHYS', 2, 12)]),
    'gargoyle': (6, 10, 8, [('AT_CLAW', 'AD_PHYS', 2, 6), ('AT_CLAW', 'AD_PHYS', 2, 6), ('AT_BITE', 'AD_PHYS', 2, 4)]),
    'garter snake': (1, 8, 3, [('AT_BITE', 'AD_PHYS', 1, 2)]),
    'gas spore': (1, 3, 2, [('AT_BOOM', 'AD_PHYS', 4, 6)]),
    'gecko': (1, 6, 2, [('AT_BITE', 'AD_PHYS', 1, 3)]),
    'gelatinous cube': (6, 6, 8, [('AT_TUCH', 'AD_PLYS', 2, 4), ('AT_NONE', 'AD_PLYS', 1, 4)]),
    'ghost': (10, 3, 12, [('AT_TUCH', 'AD_PHYS', 1, 1)]),
    'ghoul': (3, 6, 5, [('AT_CLAW', 'AD_PLYS', 1, 2), ('AT_CLAW', 'AD_PHYS', 1, 3)]),
    'giant': (6, 6, 8, [('AT_WEAP', 'AD_PHYS', 2, 10)]),
    'giant ant': (2, 18, 4, [('AT_BITE', 'AD_PHYS', 1, 4)]),
    'giant bat': (2, 22, 3, [('AT_BITE', 'AD_PHYS', 1, 6)]),
    'giant beetle': (5, 6, 6, [('AT_BITE', 'AD_PHYS', 3, 6)]),
    'giant eel': (5, 9, 7, [('AT_BITE', 'AD_PHYS', 3, 6), ('AT_TUCH', 'AD_WRAP', 0, 0)]),
    'giant mimic': (9, 3, -1, [('AT_CLAW', 'AD_STCK', 3, 6), ('AT_CLAW', 'AD_STCK', 3, 6)]),
    'giant mummy': (8, 14, 10, [('AT_CLAW', 'AD_PHYS', 3, 4), ('AT_CLAW', 'AD_PHYS', 3, 4)]),
    'giant rat': (1, 10, 2, [('AT_BITE', 'AD_PHYS', 1, 3)]),
    'giant spider': (5, 15, 7, [('AT_BITE', 'AD_DRST', 2, 4)]),
    'giant zombie': (8, 8, 9, [('AT_CLAW', 'AD_PHYS', 2, 8), ('AT_CLAW', 'AD_PHYS', 2, 8)]),
    'glass golem': (16, 6, 18, [('AT_CLAW', 'AD_PHYS', 2, 8), ('AT_CLAW', 'AD_PHYS', 2, 8)]),
    'glass piercer': (7, 1, 9, [('AT_BITE', 'AD_PHYS', 4, 6)]),
    'gnome': (1, 6, 3, [('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'gnome king': (5, 10, -1, [('AT_WEAP', 'AD_PHYS', 2, 6)]),
    'gnome lord': (3, 8, 4, [('AT_WEAP', 'AD_PHYS', 1, 8)]),
    'gnome mummy': (4, 10, 5, [('AT_CLAW', 'AD_PHYS', 1, 6)]),
    'gnome zombie': (1, 6, 2, [('AT_CLAW', 'AD_PHYS', 1, 5)]),
    'gnomish wizard': (3, 10, -1, [('AT_MAGC', 'AD_SPEL', 0, 0)]),
    'goblin': (0, 6, 1, [('AT_WEAP', 'AD_PHYS', 1, 4)]),
    'gold golem': (5, 9, -1, [('AT_CLAW', 'AD_PHYS', 2, 3), ('AT_CLAW', 'AD_PHYS', 2, 3)]),
    'golden naga': (10, 14, -1, [('AT_BITE', 'AD_PHYS', 2, 6), ('AT_MAGC', 'AD_SPEL', 4, 6)]),
    'golden naga hatchling': (3, 10, -1, [('AT_BITE', 'AD_PHYS', 1, 4)]),
    'gray dragon': (15, 9, 20, [('AT_BREA', 'AD_MAGM', 4, 6), ('AT_BITE', 'AD_PHYS', 3, 8), ('AT_CLAW', 'AD_PHYS', 1, 4), ('AT_CLAW', 'AD_PHYS', 1, 4)]),
    'gray ooze': (3, 1, 4, [('AT_BITE', 'AD_RUST', 2, 8)]),
    'gray unicorn': (4, 24, 6, [('AT_BUTT', 'AD_PHYS', 1, 12), ('AT_KICK', 'AD_PHYS', 1, 6)]),
    'green dragon': (15, 9, 20, [('AT_BREA', 'AD_DRST', 4, 6), ('AT_BITE', 'AD_PHYS', 3, 8), ('AT_CLAW', 'AD_PHYS', 1, 4), ('AT_CLAW', 'AD_PHYS', 1, 4)]),
    'green mold': (1, 0, 2, [('AT_NONE', 'AD_ACID', 0, 4)]),
    'green slime': (6, 6, 8, [('AT_TUCH', 'AD_SLIM', 1, 4), ('AT_NONE', 'AD_SLIM', 0, 0)]),
    'gremlin': (5, 12, 8, [('AT_CLAW', 'AD_PHYS', 1, 6), ('AT_CLAW', 'AD_PHYS', 1, 6), ('AT_BITE', 'AD_PHYS', 1, 4), ('AT_CLAW', 'AD_CURS', 0, 0)]),
    'grid bug': (0, 12, 1, [('AT_BITE', 'AD_ELEC', 1, 1)]),
    'guard': (12, 12, 14, [('AT_WEAP', 'AD_PHYS', 4, 10)]),
    'guardian naga': (12, 16, 16, [('AT_BITE', 'AD_PLYS', 1, 6), ('AT_SPIT', 'AD_DRST', 1, 6), ('AT_HUGS', 'AD_PHYS', 2, 4)]),
    'guardian naga hatchling': (3, 10, 4, [('AT_BITE', 'AD_PHYS', 1, 4)]),
    'guide': (5, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 6), ('AT_MAGC', 'AD_SPEL', 0, 0)]),
    'healer': (10, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'hell hound': (12, 14, -1, [('AT_BITE', 'AD_PHYS', 3, 6), ('AT_BREA', 'AD_FIRE', 3, 6)]),
    'hell hound pup': (7, 12, 9, [('AT_BITE', 'AD_PHYS', 2, 6), ('AT_BREA', 'AD_FIRE', 2, 6)]),
    'hezrou': (9, 6, 12, [('AT_CLAW', 'AD_PHYS', 1, 3), ('AT_CLAW', 'AD_PHYS', 1, 3), ('AT_BITE', 'AD_PHYS', 4, 4)]),
    'high priest': (25, 15, 30, [('AT_WEAP', 'AD_PHYS', 4, 10), ('AT_KICK', 'AD_PHYS', 2, 8), ('AT_MAGC', 'AD_CLRC', 2, 8), ('AT_MAGC', 'AD_CLRC', 2, 8)]),
    'hill giant': (8, 10, 10, [('AT_WEAP', 'AD_PHYS', 2, 8)]),
    'hill orc': (2, 9, 4, [('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'hobbit': (1, 9, 2, [('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'hobgoblin': (1, 9, 3, [('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'homunculus': (2, 12, 3, [('AT_BITE', 'AD_SLEE', 1, 3)]),
    'horned devil': (6, 9, 9, [('AT_WEAP', 'AD_PHYS', 1, 4), ('AT_CLAW', 'AD_PHYS', 1, 4), ('AT_BITE', 'AD_PHYS', 2, 3), ('AT_STNG', 'AD_PHYS', 1, 3)]),
    'horse': (5, 20, 7, [('AT_KICK', 'AD_PHYS', 1, 8), ('AT_BITE', 'AD_PHYS', 1, 3)]),
    'housecat': (4, 16, -1, [('AT_BITE', 'AD_PHYS', 1, 6)]),
    'human': (0, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'human mummy': (6, 12, 7, [('AT_CLAW', 'AD_PHYS', 2, 4), ('AT_CLAW', 'AD_PHYS', 2, 4)]),
    'human zombie': (4, 6, -1, [('AT_CLAW', 'AD_PHYS', 1, 8)]),
    'hunter': (5, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 4)]),
    'ice devil': (11, 6, 14, [('AT_CLAW', 'AD_PHYS', 1, 4), ('AT_CLAW', 'AD_PHYS', 1, 4), ('AT_BITE', 'AD_PHYS', 2, 4), ('AT_STNG', 'AD_COLD', 3, 4)]),
    'ice troll': (9, 10, 12, [('AT_WEAP', 'AD_PHYS', 2, 6), ('AT_CLAW', 'AD_COLD', 2, 6), ('AT_BITE', 'AD_PHYS', 2, 6)]),
    'ice vortex': (5, 20, 7, [('AT_ENGL', 'AD_COLD', 1, 6)]),
    'iguana': (2, 6, 3, [('AT_BITE', 'AD_PHYS', 1, 4)]),
    'imp': (3, 12, 4, [('AT_CLAW', 'AD_PHYS', 1, 4)]),
    'incubus': (6, 12, 8, []),
    'iron golem': (18, 6, -1, [('AT_WEAP', 'AD_PHYS', 4, 10), ('AT_BREA', 'AD_DRST', 4, 6)]),
    'iron piercer': (5, 1, 6, [('AT_BITE', 'AD_PHYS', 3, 6)]),
    'jabberwock': (15, 12, -1, [('AT_BITE', 'AD_PHYS', 2, 10), ('AT_BITE', 'AD_PHYS', 2, 10), ('AT_CLAW', 'AD_PHYS', 2, 10), ('AT_CLAW', 'AD_PHYS', 2, 10)]),
    'jackal': (0, 12, 1, [('AT_BITE', 'AD_PHYS', 1, 2)]),
    'jaguar': (4, 15, 6, [('AT_CLAW', 'AD_PHYS', 1, 4), ('AT_CLAW', 'AD_PHYS', 1, 4), ('AT_BITE', 'AD_PHYS', 1, 8)]),
    'jellyfish': (3, 3, 5, [('AT_STNG', 'AD_DRST', 3, 3)]),
    'ki-rin': (16, 18, -1, [('AT_KICK', 'AD_PHYS', 2, 4), ('AT_KICK', 'AD_PHYS', 2, 4), ('AT_BUTT', 'AD_PHYS', 3, 6), ('AT_MAGC', 'AD_SPEL', 2, 6)]),
    'killer bee': (1, 18, 5, [('AT_STNG', 'AD_DRST', 1, 3)]),
    'kitten': (2, 18, -1, [('AT_BITE', 'AD_PHYS', 1, 6)]),
    'knight': (10, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 6), ('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'kobold': (0, 6, 1, [('AT_WEAP', 'AD_PHYS', 1, 4)]),
    'kobold lord': (2, 6, -1, [('AT_WEAP', 'AD_PHYS', 2, 4)]),
    'kobold mummy': (3, 8, 4, [('AT_CLAW', 'AD_PHYS', 1, 4)]),
    'kobold shaman': (2, 6, -1, [('AT_MAGC', 'AD_SPEL', 0, 0)]),
    'kobold zombie': (0, 6, 1, [('AT_CLAW', 'AD_PHYS', 1, 4)]),
    'kraken': (20, 3, 22, [('AT_CLAW', 'AD_PHYS', 2, 4), ('AT_CLAW', 'AD_PHYS', 2, 4), ('AT_HUGS', 'AD_WRAP', 2, 6), ('AT_BITE', 'AD_PHYS', 5, 4)]),
    'large cat': (6, 15, -1, [('AT_BITE', 'AD_PHYS', 2, 4)]),
    'large dog': (6, 15, -1, [('AT_BITE', 'AD_PHYS', 2, 4)]),
    'large kobold': (1, 6, 2, [('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'large mimic': (8, 3, 9, [('AT_CLAW', 'AD_STCK', 3, 4)]),
    'leather golem': (6, 6, -1, [('AT_CLAW', 'AD_PHYS', 1, 6), ('AT_CLAW', 'AD_PHYS', 1, 6)]),
    'lemure': (3, 3, 5, [('AT_CLAW', 'AD_PHYS', 1, 3)]),
    'leocrotta': (6, 18, 8, [('AT_CLAW', 'AD_PHYS', 2, 6), ('AT_BITE', 'AD_PHYS', 2, 6), ('AT_CLAW', 'AD_PHYS', 2, 6)]),
    'leprechaun': (5, 15, 4, [('AT_CLAW', 'AD_SGLD', 1, 2)]),
    'lich': (11, 6, 14, [('AT_TUCH', 'AD_COLD', 1, 10), ('AT_MAGC', 'AD_SPEL', 0, 0)]),
    'lichen': (0, 1, 1, [('AT_TUCH', 'AD_STCK', 0, 0)]),
    'lieutenant': (10, 10, 12, [('AT_WEAP', 'AD_PHYS', 3, 4), ('AT_WEAP', 'AD_PHYS', 3, 4)]),
    'little dog': (2, 18, -1, [('AT_BITE', 'AD_PHYS', 1, 6)]),
    'lizard': (5, 6, 6, [('AT_BITE', 'AD_PHYS', 1, 6)]),
    'long worm': (9, 3, 10, [('AT_BITE', 'AD_PHYS', 2, 4)]),
    'long worm tail': (0, 0, 1, []),
    'lurker above': (10, 3, 12, [('AT_ENGL', 'AD_DGST', 1, 8)]),
    'lynx': (5, 15, 7, [('AT_CLAW', 'AD_PHYS', 1, 4), ('AT_CLAW', 'AD_PHYS', 1, 4), ('AT_BITE', 'AD_PHYS', 1, 10)]),
    'mail daemon': (56, 24, -1, []),
    'manes': (1, 3, 3, [('AT_CLAW', 'AD_PHYS', 1, 3), ('AT_CLAW', 'AD_PHYS', 1, 3), ('AT_BITE', 'AD_PHYS', 1, 4)]),
    'marilith': (7, 12, 11, [('AT_WEAP', 'AD_PHYS', 2, 4), ('AT_WEAP', 'AD_PHYS', 2, 4), ('AT_CLAW', 'AD_PHYS', 2, 4), ('AT_CLAW', 'AD_PHYS', 2, 4), ('AT_CLAW', 'AD_PHYS', 2, 4), ('AT_CLAW', 'AD_PHYS', 2, 4)]),
    'master lich': (17, 9, -1, [('AT_TUCH', 'AD_COLD', 3, 6), ('AT_MAGC', 'AD_SPEL', 0, 0)]),
    'master mind flayer': (13, 12, 19, [('AT_WEAP', 'AD_PHYS', 1, 8), ('AT_TENT', 'AD_DRIN', 2, 1), ('AT_TENT', 'AD_DRIN', 2, 1), ('AT_TENT', 'AD_DRIN', 2, 1), ('AT_TENT', 'AD_DRIN', 2, 1), ('AT_TENT', 'AD_DRIN', 2, 1)]),
    'mastodon': (20, 12, 22, [('AT_BUTT', 'AD_PHYS', 4, 8), ('AT_BUTT', 'AD_PHYS', 4, 8)]),
    'mind flayer': (9, 12, 13, [('AT_WEAP', 'AD_PHYS', 1, 4), ('AT_TENT', 'AD_DRIN', 2, 1), ('AT_TENT', 'AD_DRIN', 2, 1), ('AT_TENT', 'AD_DRIN', 2, 1)]),
    'minotaur': (15, 15, 17, [('AT_CLAW', 'AD_PHYS', 3, 10), ('AT_CLAW', 'AD_PHYS', 3, 10), ('AT_BUTT', 'AD_PHYS', 2, 8)]),
    'monk': (10, 12, -1, [('AT_CLAW', 'AD_PHYS', 1, 8), ('AT_KICK', 'AD_PHYS', 1, 8)]),
    'monkey': (2, 12, 4, [('AT_CLAW', 'AD_SITM', 0, 0), ('AT_BITE', 'AD_PHYS', 1, 3)]),
    'mountain centaur': (6, 20, 9, [('AT_WEAP', 'AD_PHYS', 1, 10), ('AT_KICK', 'AD_PHYS', 1, 6), ('AT_KICK', 'AD_PHYS', 1, 6)]),
    'mountain nymph': (3, 12, 5, [('AT_CLAW', 'AD_SITM', 0, 0), ('AT_CLAW', 'AD_SEDU', 0, 0)]),
    'mumak': (5, 9, 7, [('AT_BUTT', 'AD_PHYS', 4, 12), ('AT_BITE', 'AD_PHYS', 2, 6)]),
    'nalfeshnee': (11, 9, 15, [('AT_CLAW', 'AD_PHYS', 1, 4), ('AT_CLAW', 'AD_PHYS', 1, 4), ('AT_BITE', 'AD_PHYS', 2, 4), ('AT_MAGC', 'AD_SPEL', 0, 0)]),
    'neanderthal': (5, 12, -1, [('AT_WEAP', 'AD_PHYS', 2, 4)]),
    'newt': (0, 6, 1, [('AT_BITE', 'AD_PHYS', 1, 2)]),
    'ninja': (5, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 8), ('AT_WEAP', 'AD_PHYS', 1, 8)]),
    'nurse': (11, 6, -1, [('AT_CLAW', 'AD_HEAL', 2, 6)]),
    'ochre jelly': (6, 3, 8, [('AT_ENGL', 'AD_ACID', 3, 6), ('AT_NONE', 'AD_ACID', 3, 6)]),
    'ogre': (5, 10, 7, [('AT_WEAP', 'AD_PHYS', 2, 5)]),
    'ogre king': (9, 14, -1, [('AT_WEAP', 'AD_PHYS', 3, 5)]),
    'ogre lord': (7, 12, 9, [('AT_WEAP', 'AD_PHYS', 2, 6)]),
    'orange dragon': (15, 9, 20, [('AT_BREA', 'AD_SLEE', 4, 25), ('AT_BITE', 'AD_PHYS', 3, 8), ('AT_CLAW', 'AD_PHYS', 1, 4), ('AT_CLAW', 'AD_PHYS', 1, 4)]),
    'orc': (1, 9, 3, [('AT_WEAP', 'AD_PHYS', 1, 8)]),
    'orc mummy': (5, 10, 6, [('AT_CLAW', 'AD_PHYS', 1, 6)]),
    'orc shaman': (3, 9, -1, [('AT_MAGC', 'AD_SPEL', 0, 0)]),
    'orc zombie': (2, 6, 3, [('AT_CLAW', 'AD_PHYS', 1, 6)]),
    'orc-captain': (5, 5, -1, [('AT_WEAP', 'AD_PHYS', 2, 4), ('AT_WEAP', 'AD_PHYS', 2, 4)]),
    'owlbear': (5, 12, 7, [('AT_CLAW', 'AD_PHYS', 1, 6), ('AT_CLAW', 'AD_PHYS', 1, 6), ('AT_HUGS', 'AD_PHYS', 2, 8)]),
    'page': (5, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 6), ('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'panther': (5, 15, 7, [('AT_CLAW', 'AD_PHYS', 1, 6), ('AT_CLAW', 'AD_PHYS', 1, 6), ('AT_BITE', 'AD_PHYS', 1, 10)]),
    'paper golem': (3, 12, -1, [('AT_CLAW', 'AD_PHYS', 1, 3)]),
    'piranha': (5, 12, 6, [('AT_BITE', 'AD_PHYS', 2, 6)]),
    'pit fiend': (13, 6, 16, [('AT_WEAP', 'AD_PHYS', 4, 2), ('AT_WEAP', 'AD_PHYS', 4, 2), ('AT_HUGS', 'AD_PHYS', 2, 4)]),
    'pit viper': (6, 15, 9, [('AT_BITE', 'AD_DRST', 1, 4), ('AT_BITE', 'AD_DRST', 1, 4)]),
    'plains centaur': (4, 18, 6, [('AT_WEAP', 'AD_PHYS', 1, 6), ('AT_KICK', 'AD_PHYS', 1, 6)]),
    'pony': (3, 16, 4, [('AT_KICK', 'AD_PHYS', 1, 6), ('AT_BITE', 'AD_PHYS', 1, 2)]),
    'priest': (10, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'priestess': (10, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'prisoner': (12, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'purple worm': (15, 9, 17, [('AT_BITE', 'AD_PHYS', 2, 8), ('AT_ENGL', 'AD_DGST', 1, 10)]),
    'pyrolisk': (6, 6, 8, [('AT_GAZE', 'AD_FIRE', 2, 6)]),
    'python': (6, 3, 8, [('AT_BITE', 'AD_PHYS', 1, 4), ('AT_TUCH', 'AD_PHYS', 0, 0), ('AT_HUGS', 'AD_WRAP', 1, 4), ('AT_HUGS', 'AD_PHYS', 2, 4)]),
    'quantum mechanic': (7, 12, 9, [('AT_CLAW', 'AD_TLPT', 1, 4)]),
    'quasit': (3, 15, 7, [('AT_CLAW', 'AD_DRDX', 1, 2), ('AT_CLAW', 'AD_DRDX', 1, 2), ('AT_BITE', 'AD_PHYS', 1, 4)]),
    'queen bee': (9, 24, -1, [('AT_STNG', 'AD_DRST', 1, 8)]),
    'quivering blob': (5, 1, 6, [('AT_TUCH', 'AD_PHYS', 1, 8)]),
    'rabid rat': (2, 12, 4, [('AT_BITE', 'AD_DRCO', 2, 4)]),
    'ranger': (10, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 4)]),
    'raven': (4, 20, 6, [('AT_BITE', 'AD_PHYS', 1, 6), ('AT_CLAW', 'AD_BLND', 1, 6)]),
    'red dragon': (15, 9, 20, [('AT_BREA', 'AD_FIRE', 6, 6), ('AT_BITE', 'AD_PHYS', 3, 8), ('AT_CLAW', 'AD_PHYS', 1, 4), ('AT_CLAW', 'AD_PHYS', 1, 4)]),
    'red mold': (1, 0, 2, [('AT_NONE', 'AD_FIRE', 0, 4)]),
    'red naga': (6, 12, 8, [('AT_BITE', 'AD_PHYS', 2, 4), ('AT_BREA', 'AD_FIRE', 2, 6)]),
    'red naga hatchling': (3, 10, 4, [('AT_BITE', 'AD_PHYS', 1, 4)]),
    'rock mole': (3, 3, 4, [('AT_BITE', 'AD_PHYS', 1, 6)]),
    'rock piercer': (3, 1, 4, [('AT_BITE', 'AD_PHYS', 2, 6)]),
    'rock troll': (9, 12, 12, [('AT_WEAP', 'AD_PHYS', 3, 6), ('AT_CLAW', 'AD_PHYS', 2, 8), ('AT_BITE', 'AD_PHYS', 2, 6)]),
    'rogue': (10, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 6), ('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'rope golem': (4, 9, 6, [('AT_CLAW', 'AD_PHYS', 1, 4), ('AT_CLAW', 'AD_PHYS', 1, 4), ('AT_HUGS', 'AD_PHYS', 6, 1)]),
    'roshi': (5, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 8), ('AT_WEAP', 'AD_PHYS', 1, 8)]),
    'rothe': (2, 9, 4, [('AT_CLAW', 'AD_PHYS', 1, 3), ('AT_BITE', 'AD_PHYS', 1, 3), ('AT_BITE', 'AD_PHYS', 1, 8)]),
    'rust monster': (5, 18, 8, [('AT_TUCH', 'AD_RUST', 0, 0), ('AT_TUCH', 'AD_RUST', 0, 0), ('AT_NONE', 'AD_RUST', 0, 0)]),
    'salamander': (8, 12, 12, [('AT_WEAP', 'AD_PHYS', 2, 8), ('AT_TUCH', 'AD_FIRE', 1, 6), ('AT_HUGS', 'AD_PHYS', 2, 6), ('AT_HUGS', 'AD_FIRE', 3, 6)]),
    'samurai': (10, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 8), ('AT_WEAP', 'AD_PHYS', 1, 8)]),
    'sandestin': (13, 12, 15, [('AT_WEAP', 'AD_PHYS', 2, 6), ('AT_WEAP', 'AD_PHYS', 2, 6)]),
    'sasquatch': (7, 15, 9, [('AT_CLAW', 'AD_PHYS', 1, 6), ('AT_CLAW', 'AD_PHYS', 1, 6), ('AT_KICK', 'AD_PHYS', 1, 8)]),
    'scorpion': (5, 15, 8, [('AT_CLAW', 'AD_PHYS', 1, 2), ('AT_CLAW', 'AD_PHYS', 1, 2), ('AT_STNG', 'AD_DRST', 1, 4)]),
    'sergeant': (8, 10, 10, [('AT_WEAP', 'AD_PHYS', 2, 6)]),
    'sewer rat': (0, 12, 1, [('AT_BITE', 'AD_PHYS', 1, 3)]),
    'shade': (12, 10, 14, [('AT_TUCH', 'AD_PLYS', 2, 6), ('AT_TUCH', 'AD_SLOW', 1, 6)]),
    'shark': (7, 12, 9, [('AT_BITE', 'AD_PHYS', 5, 6)]),
    'shimmering dragon': (15, 9, -1, [('AT_BREA', 'AD_MAGM', 4, 6), ('AT_BITE', 'AD_PHYS', 3, 8), ('AT_CLAW', 'AD_PHYS', 1, 4), ('AT_CLAW', 'AD_PHYS', 1, 4)]),
    'shocking sphere': (6, 13, -1, [('AT_EXPL', 'AD_ELEC', 4, 6)]),
    'shopkeeper': (12, 18, -1, [('AT_WEAP', 'AD_PHYS', 4, 4), ('AT_WEAP', 'AD_PHYS', 4, 4)]),
    'shrieker': (3, 1, 2, []),
    'silver dragon': (15, 9, -1, [('AT_BREA', 'AD_COLD', 4, 6), ('AT_BITE', 'AD_PHYS', 3, 8), ('AT_CLAW', 'AD_PHYS', 1, 4), ('AT_CLAW', 'AD_PHYS', 1, 4)]),
    'skeleton': (12, 8, 14, [('AT_WEAP', 'AD_PHYS', 2, 6), ('AT_TUCH', 'AD_SLOW', 1, 6)]),
    'small mimic': (7, 3, 8, [('AT_CLAW', 'AD_PHYS', 3, 4)]),
    'snake': (4, 15, 6, [('AT_BITE', 'AD_DRST', 1, 6)]),
    'soldier': (6, 10, 8, [('AT_WEAP', 'AD_PHYS', 1, 8)]),
    'soldier ant': (3, 18, 6, [('AT_BITE', 'AD_PHYS', 2, 4), ('AT_STNG', 'AD_DRST', 3, 4)]),
    'spotted jelly': (5, 0, 6, [('AT_NONE', 'AD_ACID', 0, 6)]),
    'stalker': (8, 12, 9, [('AT_CLAW', 'AD_PHYS', 4, 4)]),
    'steam vortex': (7, 22, 9, [('AT_ENGL', 'AD_FIRE', 1, 8)]),
    'stone giant': (6, 6, 8, [('AT_WEAP', 'AD_PHYS', 2, 10)]),
    'stone golem': (14, 6, 15, [('AT_CLAW', 'AD_PHYS', 3, 8)]),
    'storm giant': (16, 12, 19, [('AT_WEAP', 'AD_PHYS', 2, 12)]),
    'straw golem': (3, 12, 4, [('AT_CLAW', 'AD_PHYS', 1, 2), ('AT_CLAW', 'AD_PHYS', 1, 2)]),
    'student': (5, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'succubus': (6, 12, 8, []),
    'tengu': (6, 13, 7, [('AT_BITE', 'AD_PHYS', 1, 7)]),
    'thug': (5, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 6), ('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'tiger': (6, 12, 8, [('AT_CLAW', 'AD_PHYS', 2, 4), ('AT_CLAW', 'AD_PHYS', 2, 4), ('AT_BITE', 'AD_PHYS', 1, 10)]),
    'titan': (16, 18, 20, [('AT_WEAP', 'AD_PHYS', 2, 8), ('AT_MAGC', 'AD_SPEL', 0, 0)]),
    'titanothere': (12, 12, 13, [('AT_CLAW', 'AD_PHYS', 2, 8)]),
    'tourist': (10, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 6), ('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'trapper': (12, 3, 14, [('AT_ENGL', 'AD_DGST', 1, 10)]),
    'troll': (7, 12, 9, [('AT_WEAP', 'AD_PHYS', 4, 2), ('AT_CLAW', 'AD_PHYS', 4, 2), ('AT_BITE', 'AD_PHYS', 2, 6)]),
    'umber hulk': (9, 6, 12, [('AT_CLAW', 'AD_PHYS', 3, 4), ('AT_CLAW', 'AD_PHYS', 3, 4), ('AT_BITE', 'AD_PHYS', 2, 5), ('AT_GAZE', 'AD_CONF', 0, 0)]),
    'valkyrie': (10, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 8), ('AT_WEAP', 'AD_PHYS', 1, 8)]),
    'vampire': (10, 12, 12, [('AT_CLAW', 'AD_PHYS', 1, 6), ('AT_BITE', 'AD_DRLI', 1, 6)]),
    'vampire bat': (5, 20, 7, [('AT_BITE', 'AD_PHYS', 1, 6), ('AT_BITE', 'AD_DRST', 0, 0)]),
    'vampire lord': (12, 14, -1, [('AT_CLAW', 'AD_PHYS', 1, 8), ('AT_BITE', 'AD_DRLI', 1, 8)]),
    'vampire mage': (20, 14, -1, [('AT_CLAW', 'AD_DRLI', 2, 8), ('AT_BITE', 'AD_DRLI', 1, 8), ('AT_MAGC', 'AD_SPEL', 2, 6)]),
    'violet fungus': (3, 1, 5, [('AT_TUCH', 'AD_PHYS', 1, 4), ('AT_TUCH', 'AD_STCK', 0, 0)]),
    'vorpal jabberwock': (20, 12, -1, [('AT_BITE', 'AD_PHYS', 3, 10), ('AT_BITE', 'AD_PHYS', 3, 10), ('AT_CLAW', 'AD_PHYS', 3, 10), ('AT_CLAW', 'AD_PHYS', 3, 10)]),
    'vrock': (8, 12, 11, [('AT_CLAW', 'AD_PHYS', 1, 4), ('AT_CLAW', 'AD_PHYS', 1, 4), ('AT_CLAW', 'AD_PHYS', 1, 8), ('AT_CLAW', 'AD_PHYS', 1, 8), ('AT_BITE', 'AD_PHYS', 1, 6)]),
    'warg': (7, 12, 8, [('AT_BITE', 'AD_PHYS', 2, 6)]),
    'warhorse': (7, 24, 9, [('AT_KICK', 'AD_PHYS', 1, 10), ('AT_BITE', 'AD_PHYS', 1, 4)]),
    'warrior': (5, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 8), ('AT_WEAP', 'AD_PHYS', 1, 8)]),
    'watch captain': (10, 10, 12, [('AT_WEAP', 'AD_PHYS', 3, 4), ('AT_WEAP', 'AD_PHYS', 3, 4)]),
    'watchman': (6, 10, 8, [('AT_WEAP', 'AD_PHYS', 1, 8)]),
    'water demon': (8, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 3), ('AT_CLAW', 'AD_PHYS', 1, 3), ('AT_BITE', 'AD_PHYS', 1, 3)]),
    'water elemental': (8, 6, 10, [('AT_CLAW', 'AD_PHYS', 5, 6)]),
    'water moccasin': (4, 15, 7, [('AT_BITE', 'AD_DRST', 1, 6)]),
    'water nymph': (3, 12, 5, [('AT_CLAW', 'AD_SITM', 0, 0), ('AT_CLAW', 'AD_SEDU', 0, 0)]),
    'water troll': (11, 14, 13, [('AT_WEAP', 'AD_PHYS', 2, 8), ('AT_CLAW', 'AD_PHYS', 2, 8), ('AT_BITE', 'AD_PHYS', 2, 6)]),
    'werejackal': (2, 12, 3, [('AT_WEAP', 'AD_PHYS', 2, 4)]),
    'wererat': (2, 12, 3, [('AT_WEAP', 'AD_PHYS', 2, 4)]),
    'werewolf': (5, 12, 6, [('AT_WEAP', 'AD_PHYS', 2, 4)]),
    'white dragon': (15, 9, 20, [('AT_BREA', 'AD_COLD', 4, 6), ('AT_BITE', 'AD_PHYS', 3, 8), ('AT_CLAW', 'AD_PHYS', 1, 4), ('AT_CLAW', 'AD_PHYS', 1, 4)]),
    'white unicorn': (4, 24, 6, [('AT_BUTT', 'AD_PHYS', 1, 12), ('AT_KICK', 'AD_PHYS', 1, 6)]),
    'winged gargoyle': (9, 15, -1, [('AT_CLAW', 'AD_PHYS', 3, 6), ('AT_CLAW', 'AD_PHYS', 3, 6), ('AT_BITE', 'AD_PHYS', 3, 4)]),
    'winter wolf': (7, 12, 9, [('AT_BITE', 'AD_PHYS', 2, 6), ('AT_BREA', 'AD_COLD', 2, 6)]),
    'winter wolf cub': (5, 12, 7, [('AT_BITE', 'AD_PHYS', 1, 8), ('AT_BREA', 'AD_COLD', 1, 6)]),
    'wizard': (10, 12, -1, [('AT_WEAP', 'AD_PHYS', 1, 6)]),
    'wolf': (5, 12, 6, [('AT_BITE', 'AD_PHYS', 2, 4)]),
    'wood golem': (7, 3, -1, [('AT_CLAW', 'AD_PHYS', 3, 4)]),
    'wood nymph': (3, 12, 5, [('AT_CLAW', 'AD_SITM', 0, 0), ('AT_CLAW', 'AD_SEDU', 0, 0)]),
    'woodchuck': (3, 3, 4, [('AT_BITE', 'AD_PHYS', 1, 6)]),
    'wraith': (6, 12, 8, [('AT_TUCH', 'AD_DRLI', 1, 6)]),
    'wumpus': (8, 3, 9, [('AT_BITE', 'AD_PHYS', 3, 6)]),
    'xan': (7, 18, 9, [('AT_STNG', 'AD_LEGS', 1, 4)]),
    'xorn': (8, 9, 11, [('AT_CLAW', 'AD_PHYS', 1, 3), ('AT_CLAW', 'AD_PHYS', 1, 3), ('AT_CLAW', 'AD_PHYS', 1, 3), ('AT_BITE', 'AD_PHYS', 4, 6)]),
    'yellow dragon': (15, 9, 20, [('AT_BREA', 'AD_ACID', 4, 6), ('AT_BITE', 'AD_PHYS', 3, 8), ('AT_CLAW', 'AD_PHYS', 1, 4), ('AT_CLAW', 'AD_PHYS', 1, 4)]),
    'yellow light': (3, 15, 5, [('AT_EXPL', 'AD_BLND', 10, 20)]),
    'yellow mold': (1, 0, 2, [('AT_NONE', 'AD_STUN', 0, 4)]),
    'yeti': (5, 15, 7, [('AT_CLAW', 'AD_PHYS', 1, 6), ('AT_CLAW', 'AD_PHYS', 1, 6), ('AT_BITE', 'AD_PHYS', 1, 4)]),
    'zruty': (9, 8, 11, [('AT_CLAW', 'AD_PHYS', 3, 4), ('AT_CLAW', 'AD_PHYS', 3, 4), ('AT_BITE', 'AD_PHYS', 3, 6)]),
}
